import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import { Navbar, Footer } from "@/components";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
